# Generated by Django 4.1.7 on 2023-04-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_rename_timestap_enroll_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='Fullname',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='Referenec',
        ),
    ]
